# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - binloglive

on:
  push:
    branches:
      - live

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Build with dotnet
      run: dotnet build MSBuildStructuredLog.sln --configuration Release 

    - name: dotnet publish
      run: dotnet publish "Blazor App\StructuredLogViewerWASM.csproj" -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'binloglive'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_56800b135da94579939f651d44446204 }}
        package: ${{env.DOTNET_ROOT}}/myapp 
